name: Main
on: [pull_request]

jobs:
  base:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ruby: [2.7, 3.0, 3.1, 3.2]
    name: Gemfile - Ruby ${{ matrix.ruby }}
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: textacular_test
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
        ports: ["5432:5432"]
    env:
      BUNDLE_GEMFILE: Gemfile

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Setup database
        run: |
          cp test/config.github.yml test/config.yml
          bundle exec rake db:migrate

      - name: Run tests
        run: bundle exec rake

  versions:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: textacular_test
          POSTGRES_PASSWORD: password
          POSTGRES_USER: postgres
        ports: ["5432:5432"]
    strategy:
      fail-fast: false
      matrix:
        ruby: [3.0, 3.1, 3.2]
        rails: ['6.0', '6.1', '7.0', '7.1']
        include:
          - rails: '5.0'
            ruby: 2.7
          - rails: '5.1'
            ruby: 2.7
          - rails: '5.2'
            ruby: 2.7
    name: Ruby ${{ matrix.ruby }} - Rails ${{ matrix.rails }}
    env:
      BUNDLE_GEMFILE: ${{ github.workspace }}/gemfiles/activerecord-${{ matrix.rails }}.gemfile

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Setup database
        run: |
          cp test/config.github.yml test/config.yml
          bundle exec rake db:migrate

      - name: Run tests
        run: bundle exec rake
